### ISSUE TITLE
Top 10 temperature

### ISSUE THREAD

**Issue by IcyPalm** [Jarinus/2.1-unwdmi-web#10]
# Top 10 temperature of past 24 hours per longitude, same as Kyoto
Fixed timeframe: 10:00 to 10:00 local time, daily based

Suggestion: Timeframe maybe flexible

Data on screen within 5 seconds
Availability 98% monthly

-[ ] Remove nonrelevant data
-[ ] Clickable measurement links

**Comment by Jarinus** [comment]
@IcyPalm Started on this issue in the 'backend' branch!

**Comment by IcyPalm** [comment]
-[ ] Remove nonrelevant data
-[ ] Clickable measurement links
