### ISSUE TITLE
All weatherdata same longitude

### ISSUE THREAD

**Issue by IcyPalm** [Jarinus/2.1-unwdmi-web#7]
# All weatherdata of all the weatherstation on the same longitude as Kyoto
Only when temperature is below 20 degrees
Every week on Thursday at 9:00 local
Timespan is one week

Data on screen within 30 seconds
Availability 95% monthly	

Question: average temperature of the whole week or extremes?

**Comment by Jarinus** [comment]
@IcyPalm Started on this issue based on the top 10 temperatures issue.

**Comment by Jarinus** [comment]
I believe I finished with the back-end part of this issue.

**Comment by goto-bus-stop** [comment]
3ae3bf9

**Comment by IcyPalm** [comment]
@goto-bus-stop implement collumn sorting
