### ISSUE TITLE
Graphical rainfall information of ANY station worldwide

### ISSUE THREAD

**Issue by IcyPalm** [Jarinus/2.1-unwdmi-web#8]
# Graphical rainfall information of ANY station worldwide for the current day
Last 24 hours, line graph, bar graph per hour
Line and Bar graph hover with label with amount of rain
Rain in Milimeters
Worldmap view and list view

Josephine: (Real time data) She said something about realtime data, not sure if really realtime or just fancy IT term usage

Data on screen within 25 seconds

**Comment by goto-bus-stop** [comment]
Realtime probably means "most recent", but we can do better ;)

World map view ideas:

 * OpenStreetMap?
 * Pan & Zoom
 * Rainfall heatmap using Canvas

**Comment by tieskedh** [comment]
Could have: save interactive map(position etc.)?
As should have: download image of map?

**Comment by Jarinus** [comment]
Started on this issue on 'back-end'.

Will return an array of rainfall information, indexed by its associative station number.

Example:

array(
1 => array(4.20, 13.37),
2 => array(1.00, 2.00)
);

**Comment by goto-bus-stop** [comment]
For the world map, we need the most recent rainfall levels by _location_, so something like:

```js
[
  { "long": 123.23, "lat": 73.3, "rain": 3.2 },
  { "long": 32.341, "lat": 64.635, "rain": 1.6 },
  // …
]
```

**Comment by goto-bus-stop** [comment]
Todo:

* [ ] Rainfall heatmap, probably just use the terrible one I have locally. ♥
* [ ] Graphs on Stations page. Use Chart.js component

**Comment by goto-bus-stop** [comment]
not sure how to make Chart.js + deku work. will just duct tape stuff together bypassing deku for this case I guess.
