### ISSUE TITLE
Raw Data history

### ISSUE THREAD

**Issue by IcyPalm** [Jarinus/2.1-unwdmi-web#9]
# Raw Data history 
Excel document, easily importable in Excel, format not important(xls(x) vs. csv)
Selection of time period
Maximum of three months ago
Excel cap = 1,048,576 rows

Filtering options:
 - Filtering on country(as suggested by Stadman)
 - Maybe more (just to show off)

**Comment by tieskedh** [comment]
We don't support excel previous to 2007?

**Comment by IcyPalm** [comment]
Meh, nobody gives a damn about 2003

**Comment by jlsa** [comment]
Everyone did way back when!

**Comment by tieskedh** [comment]
Is the filtering as in diggerent sheets or different downloads?
